/*
 * Synpasis.id backend challenge
 *
 * Demo Server
 *
 * API version: 1.0.0
 * Contact: hadinaufal26@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SubCategory struct {

	PrScId int32 `json:"prScId,omitempty"`

	PrScName string `json:"prScName,omitempty"`

	PrScImageUrl string `json:"prScImageUrl,omitempty"`

	PrScIsActive bool `json:"prScIsActive,omitempty"`
}
