/*
 * Synpasis.id backend challenge
 *
 * Demo Server
 *
 * API version: 1.0.0
 * Contact: hadinaufal26@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Category struct {

	PrId int32 `json:"prId,omitempty"`

	PrName string `json:"prName,omitempty"`

	PrImageUrl string `json:"prImageUrl,omitempty"`

	PrIsActive bool `json:"prIsActive,omitempty"`

	SubCategories []SubCategory `json:"subCategories,omitempty"`
}
